# Generated by Django 3.2.11 on 2022-02-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0002_auto_20220217_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='up_date',
            new_name='relese_date',
        ),
    ]
