# Generated by Django 3.2.11 on 2022-02-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0004_book_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_updated_on', models.DateTimeField(auto_created=True)),
                ('data_created_on', models.DateField(auto_now=True)),
                ('country_name', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
