# Generated by Django 3.2.11 on 2022-01-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_auto_20220127_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role_type',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
